# Generated by Django 3.0.6 on 2020-05-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('annotated', models.BooleanField()),
            ],
        ),
    ]
