# Generated by Django 3.0.6 on 2020-05-13 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200513_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project',
            new_name='name',
        ),
    ]
